<?php
class AboutPageSchema extends GenericSchema
{
    public function mustRenderOnPage()
    {
        global $post;

        return $post !== null && Markapp_Schema_Matcher::isAboutPage($post); // TODO: Change the autogenerated stub
    }

    public function schema()
    {
        global $my_seo_settings_about_page_options;
        global $my_seo_settings_options;

        $data = [];

        $data["@context"] = "http://schema.org";
			$data["@type"] = "WebPage";
			$data["@id"] = "schema:WebPage";
		$data["mainEntity"] = [
			"@type" => "AboutPage",
			"@id" => "schema:AboutPage",
			"name" => "About Page",
			"lastReviewed" => get_the_modified_date( 'c' ),
			"reviewedBy" => [
				"@type" => "Organization",
		"@id" => "schema:Organization",
		"brand" =>[
                "@type" => "Brand",
				"id" => "schema:Brand",
                "name"  => $my_seo_settings_about_page_options['generate_json_ld_about_page_brand'] ?? null,
                "logo"  => array(
                    "@type" => "ImageObject",
                    "url"   => $options['generate_json_ld_localbusiness_brand_logo_url'] ?? null,
                )
			],
				"contactPoint" => [
     "@type" => "ContactPoint",
	  "email" => $my_seo_settings_about_page_options['generate_json_ld_about_page_email'] ?? null,
      "telephone" => $my_seo_settings_about_page_options['generate_json_ld_about_page_telephone'] ?? null,
      "contactType" => $my_seo_settings_about_page_options['generate_json_ld_about_page_contacttype'] ?? null,
      "areaServed" => $my_seo_settings_about_page_options['generate_json_ld_about_page_area_served'] ?? null],
		],
		"about" => [
			"@type" => "CreativeWork",
			"@id" => "schema:CreativeWork",
			"name" => get_the_title(),
			"description" => get_the_excerpt(55)]
		
    ];
        $data["copyrightYear"] = $my_seo_settings_about_page_options['generate_json_ld_about_page_copyright_year'] ?? null;
        $data["headline"] = get_the_title();
        $data["relatedLink"] = $my_seo_settings_about_page_options['generate_json_ld_about_page_related_link'] ?? null;
        $data["specialty"] = array(
                "@type"  => "Specialty",
				"@id" => "schema:Specialty",
                "description" => $my_seo_settings_about_page_options['generate_json_ld_about_page_speciality_description'] ?? null,
                "name" => $my_seo_settings_about_page_options['generate_json_ld_about_page_speciality_name'] ?? null
            );
        $data["inLanguage"]  = [
                "@type" => "Language",
				"@id" => "schema:Language",		
                "name" => $my_seo_settings_options["generate_json_ld_fpwebpage_inlanguage"] ?? null 
            ];
            $data["primaryImageOfPage"] = get_the_post_thumbnail_url();
		$data["sameAs"] = array(
		$my_seo_settings_about_page_options['generate_json_ld_about_page_facebook'] ?? null,
		$my_seo_settings_about_page_options['generate_json_ld_about_page_instagram'] ?? null,
		$my_seo_settings_about_page_options['generate_json_ld_about_page_twitter'] ?? null,
		$my_seo_settings_about_page_options['generate_json_ld_about_page_linkedin'] ?? null,
		$my_seo_settings_about_page_options['generate_json_ld_about_page_podcast'] ?? null);

        return $data;
    }

    public function settings()
    {
        $settings = AboutPageSettings::instance();
        $settings->initDefaultSection();
        $settings->initSidebarSettingsPage(get_class($this));
        $settings->renderSidebarForm();
    }

}